{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ printf "%s-external" (include "syncbit.fullname" .) }}
  labels:
    {{- include "syncbit.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore.name }}
    kind: {{ .Values.externalSecrets.secretStore.kind }}
  target:
    name: {{ printf "%s-external" (include "syncbit.fullname" .) }}
    creationPolicy: Owner
  data:
  - secretKey: fitbit-client-id
    remoteRef:
      key: {{ .Values.externalSecrets.secrets.fitbitClientId }}
  - secretKey: fitbit-client-secret
    remoteRef:
      key: {{ .Values.externalSecrets.secrets.fitbitClientSecret }}
  - secretKey: victoria-user
    remoteRef:
      key: {{ .Values.externalSecrets.secrets.victoriaUser }}
  - secretKey: victoria-password
    remoteRef:
      key: {{ .Values.externalSecrets.secrets.victoriaPassword }}
  - secretKey: victoria-endpoint
    remoteRef:
      key: {{ .Values.externalSecrets.secrets.victoriaEndpoint }}
{{- end }}
