{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ printf "%s-external" (include "syncbit.fullname" .) }}
  labels:
    {{- include "syncbit.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore.name }}
    kind: {{ .Values.externalSecrets.secretStore.kind }}
  target:
    name: {{ printf "%s-external" (include "syncbit.fullname" .) }}
    creationPolicy: Owner
  data:
  - secretKey: fitbit-client-id
    remoteRef:
      key: syncbit
      property: FITBIT_CLIENT_ID
  - secretKey: fitbit-client-secret
    remoteRef:
      key: syncbit
      property: FITBIT_CLIENT_SECRET
  - secretKey: victoria-user
    remoteRef:
      key: victoria-metrics
      property: USER
  - secretKey: victoria-password
    remoteRef:
      key: victoria-metrics
      property: PASSWORD
  - secretKey: victoria-endpoint
    remoteRef:
      key: victoria-metrics
      property: ENDPOINT
{{- end }}
