{{- if not .Values.externalSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-secrets" (include "syncbit.fullname" .) }}
  labels:
    {{- include "syncbit.labels" . | nindent 4 }}
type: Opaque
data:
  fitbit-client-id: {{ .Values.secrets.fitbitClientId | b64enc | quote }}
  fitbit-client-secret: {{ .Values.secrets.fitbitClientSecret | b64enc | quote }}
  victoria-user: {{ .Values.secrets.victoriaUser | b64enc | quote }}
  victoria-password: {{ .Values.secrets.victoriaPassword | b64enc | quote }}
  victoria-endpoint: {{ .Values.secrets.victoriaEndpoint | b64enc | quote }}
{{- end }}
